package ec.edu.ups.vista;

import ec.edu.ups.modelo.Persona;
import ec.edu.ups.controladorExepcion.ErrorCedula;
import ec.edu.ups.controladorExepcion.ErrorApellidoLetras;
import ec.edu.ups.controladorExepcion.ErrrorNombreLetras;
import ec.edu.ups.controladorExepcion.ErrorEdad;
import ec.edu.ups.controladorExepcion.ErrorNombreDosNomres;
import ec.edu.ups.controladorExepcion.ErrorApellidoDosApellidos;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Edison
 */
public class ModificarPersona extends javax.swing.JInternalFrame {

    /**
     * Creates new form ModificarCliente
     */
    int posicion;

    public ModificarPersona() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLSalario = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        txtPosicion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        txtApellido = new javax.swing.JTextField();
        jLCedula = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLApellido = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jLNombre = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLEdad = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        jLFecha = new javax.swing.JLabel();
        txtSalario = new javax.swing.JTextField();
        jLCelular = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();

        jLSalario.setText("Salario");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("Posicion");

        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaKeyTyped(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });

        jLCedula.setText("ID");

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        jLApellido.setText("Apellido");

        jLNombre.setText("Nombre");

        txtFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFechaKeyTyped(evt);
            }
        });

        jLEdad.setText("Edad");

        txtCelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCelularKeyTyped(evt);
            }
        });

        jLFecha.setText("Fecha");

        jLCelular.setText("Celular");

        btnGuardar.setText("Guardar");
        btnGuardar.setToolTipText("");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLCedula)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLApellido)
                            .addComponent(jLNombre)
                            .addComponent(jLEdad)
                            .addComponent(jLFecha)
                            .addComponent(jLCelular)
                            .addComponent(jLSalario))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar))
                            .addComponent(txtCedula, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addComponent(txtApellido)
                            .addComponent(txtNombre)
                            .addComponent(txtEdad)
                            .addComponent(txtFecha)
                            .addComponent(txtCelular)
                            .addComponent(txtSalario))))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCedula)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLApellido)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEdad)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLFecha)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCelular)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLSalario)
                    .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String ruta = "Personas.ups";
        String apellido;
        String nombre;
        try {
            RandomAccessFile archivo = new RandomAccessFile(ruta, "rw");
            posicion = Integer.parseInt(txtPosicion.getText()) * 152;
            archivo.seek(posicion);
            String setNombre = archivo.readUTF();
            if (!setNombre.equals("                                                  ")) {
                String palabrasN[] = setNombre.split(" ");
                nombre = palabrasN[0] + " " + palabrasN[1];
                txtNombre.setText(nombre);

                archivo.seek(posicion + 52);
                String palabrasA[] = archivo.readUTF().split(" ");
                apellido = palabrasA[0] + " " + palabrasA[1];
                txtApellido.setText(apellido);

                archivo.seek(posicion + 104);
                txtCedula.setText(archivo.readUTF());
                archivo.seek(posicion + 116);
                txtEdad.setText(String.valueOf(archivo.readInt()));
                archivo.seek(posicion + 120);
                txtFecha.setText(archivo.readUTF());
                archivo.seek(posicion + 132);
                txtCelular.setText(archivo.readUTF());
                archivo.seek(posicion + 144);
                txtSalario.setText(String.valueOf(archivo.readDouble()));
            } else {
                JOptionPane.showMessageDialog(this, "La persona no existe", "Error", JOptionPane.OK_OPTION);
            }
            archivo.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(BuscarPersona.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException e) {
            System.out.println("Error de escritura");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String ruta = "Personas.ups";
        Persona persona = new Persona();
        String nombre = txtNombre.getText();
        String apellido = txtApellido.getText();
        int c = 0;
        try {
            RandomAccessFile archivo = new RandomAccessFile(ruta, "rw");

            persona.setNombre(nombre);
            persona.setApellido(apellido);
            persona.setCedula(txtCedula.getText());
            persona.setEdad(Integer.parseInt(txtEdad.getText()));

            if (txtCelular.getText().length() != 10) {
                JOptionPane.showMessageDialog(this, "Ingrese los dies numeros del celular", "Error celular", JOptionPane.OK_OPTION);
            } else if (txtFecha.getText().length() != 10) {
                JOptionPane.showMessageDialog(this, "Ingrese correctamente la fecha Ejm.(20/11/2000)", "Error fecha", JOptionPane.OK_OPTION);
            } else {
                archivo.seek(posicion);
                for (int i = txtNombre.getText().length() + 1; i <= 50; i++) {
                    nombre = nombre.substring(0) + " ";
                }
                archivo.writeUTF(nombre);
                for (int i = txtApellido.getText().length() + 1; i <= 50; i++) {
                    apellido = apellido.substring(0) + " ";
                }
                archivo.writeUTF(apellido);
                archivo.writeUTF(txtCedula.getText());
                archivo.writeInt(Integer.parseInt(txtEdad.getText()));
                archivo.writeUTF(txtFecha.getText());
                archivo.writeUTF(txtCelular.getText());
                archivo.writeDouble(Double.parseDouble(txtSalario.getText()));
            }
            archivo.close();
            JOptionPane.showMessageDialog(this, "Persona modificada", "Modificar Persona", JOptionPane.OK_OPTION);
            txtCedula.setText("");
            txtNombre.setText("");
            txtApellido.setText("");
            txtCelular.setText("");
            txtEdad.setText("");
            txtFecha.setText("");
            txtSalario.setText("");
            txtPosicion.setText("");
        } catch (FileNotFoundException e) {
            System.out.println("Archivo no encontrado");
        } catch (IOException e) {
            System.out.println("Error de escritura");
        } catch (ErrorApellidoDosApellidos e) {
            JOptionPane.showMessageDialog(this, "Ingrese dos apellidos", "Error apelldo", JOptionPane.OK_OPTION);
        } catch (ErrorApellidoLetras e) {
            JOptionPane.showMessageDialog(this, "apellidos", "Error apelldo", JOptionPane.OK_OPTION);
        } catch (ErrorCedula e) {
            JOptionPane.showMessageDialog(this, "CEDULA INCORRECTA", "Error Cedula", JOptionPane.OK_OPTION);
        } catch (ErrorEdad e) {
            JOptionPane.showMessageDialog(this, "Edad", "Error edad", JOptionPane.OK_OPTION);
        } catch (ErrorNombreDosNomres e) {
            JOptionPane.showMessageDialog(this, "Ingrese dos nombres", "Error nombre", JOptionPane.OK_OPTION);
        } catch (ErrrorNombreLetras e) {
            JOptionPane.showMessageDialog(this, "nombre", "Error nombre", JOptionPane.OK_OPTION);
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyTyped
        if (txtCedula.getText().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCedulaKeyTyped

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
        if (txtApellido.getText().length() == 50) {
            evt.consume();
        }
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        if (txtNombre.getText().length() == 50) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtFechaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaKeyTyped
        if (txtFecha.getText().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_txtFechaKeyTyped

    private void txtCelularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelularKeyTyped
        if (txtCelular.getText().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCelularKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLApellido;
    private javax.swing.JLabel jLCedula;
    private javax.swing.JLabel jLCelular;
    private javax.swing.JLabel jLEdad;
    private javax.swing.JLabel jLFecha;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLSalario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPosicion;
    private javax.swing.JTextField txtSalario;
    // End of variables declaration//GEN-END:variables
}
